// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd9lzJiI0qPFvY8HYsRGXOFQcs7CbfceU',
    appId: '1:872148410600:web:c3c1d4ff1e69955793a95d',
    messagingSenderId: '872148410600',
    projectId: 'bingo-bb0fb',
    authDomain: 'bingo-bb0fb.firebaseapp.com',
    storageBucket: 'bingo-bb0fb.appspot.com',
    measurementId: 'G-C3CWMY9QDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAITKE9aUgdDB-r40TsO6KKB-JxyjADn0E',
    appId: '1:872148410600:android:95713c1df2dbbcde93a95d',
    messagingSenderId: '872148410600',
    projectId: 'bingo-bb0fb',
    storageBucket: 'bingo-bb0fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChITiJazQyn6LCMvr3DZWvIVJCBQHGihw',
    appId: '1:872148410600:ios:7d2b1a271d6618c293a95d',
    messagingSenderId: '872148410600',
    projectId: 'bingo-bb0fb',
    storageBucket: 'bingo-bb0fb.appspot.com',
    iosBundleId: 'com.example.bingo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChITiJazQyn6LCMvr3DZWvIVJCBQHGihw',
    appId: '1:872148410600:ios:7d2b1a271d6618c293a95d',
    messagingSenderId: '872148410600',
    projectId: 'bingo-bb0fb',
    storageBucket: 'bingo-bb0fb.appspot.com',
    iosBundleId: 'com.example.bingo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd9lzJiI0qPFvY8HYsRGXOFQcs7CbfceU',
    appId: '1:872148410600:web:69ce149f17d098f893a95d',
    messagingSenderId: '872148410600',
    projectId: 'bingo-bb0fb',
    authDomain: 'bingo-bb0fb.firebaseapp.com',
    storageBucket: 'bingo-bb0fb.appspot.com',
    measurementId: 'G-69WT4RY8D6',
  );
}
